version: '3.8'

services:
  db:
    build: ./db
    environment:
      MYSQL_DATABASE: fitofan
      MYSQL_ROOT_PASSWORD: root
    ports:
      - "3307:3306"
    volumes:
      - db_data:/var/lib/mysql
    restart: always

  server:
    build: ./server
    ports:
      - "3000:8090"
    depends_on:
      - db

  # client:
  #   build: ./client
  #   ports:
  #     - "8084:3030"
  #   depends_on:
  #     - server

volumes:
  db_data: